// Wire-compatible subset of Osprey's synchronous coordinator API.
// Source: github.com/roostorg/osprey at 1581a02 (Apache-2.0).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/policy/osprey/rpc/v1/osprey.proto

package ospreyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdicts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Verdicts      []string               `protobuf:"bytes,3,rep,name=verdicts,proto3" json:"verdicts,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdicts) Reset() {
	*x = Verdicts{}
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdicts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdicts) ProtoMessage() {}

func (x *Verdicts) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdicts.ProtoReflect.Descriptor instead.
func (*Verdicts) Descriptor() ([]byte, []int) {
	return file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescGZIP(), []int{0}
}

func (x *Verdicts) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *Verdicts) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *Verdicts) GetVerdicts() []string {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

func (x *Verdicts) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ProcessActionRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ActionId       *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName     string                  `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionDataJson string                  `protobuf:"bytes,3,opt,name=action_data_json,json=actionDataJson,proto3" json:"action_data_json,omitempty"`
	Timestamp      *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessActionRequest) Reset() {
	*x = ProcessActionRequest{}
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessActionRequest) ProtoMessage() {}

func (x *ProcessActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessActionRequest.ProtoReflect.Descriptor instead.
func (*ProcessActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessActionRequest) GetActionId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ActionId
	}
	return nil
}

func (x *ProcessActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ProcessActionRequest) GetActionDataJson() string {
	if x != nil {
		return x.ActionDataJson
	}
	return ""
}

func (x *ProcessActionRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ProcessActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdicts      *Verdicts              `protobuf:"bytes,2,opt,name=verdicts,proto3" json:"verdicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessActionResponse) Reset() {
	*x = ProcessActionResponse{}
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessActionResponse) ProtoMessage() {}

func (x *ProcessActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessActionResponse.ProtoReflect.Descriptor instead.
func (*ProcessActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessActionResponse) GetVerdicts() *Verdicts {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

var File_internal_policy_osprey_rpc_v1_osprey_proto protoreflect.FileDescriptor

const file_internal_policy_osprey_rpc_v1_osprey_proto_rawDesc = "" +
	"\n" +
	"*internal/policy/osprey/rpc/v1/osprey.proto\x12,osprey.rpc.osprey_coordinator.sync_action.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9e\x01\n" +
	"\bVerdicts\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12\x1a\n" +
	"\bverdicts\x18\x03 \x03(\tR\bverdicts\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xdc\x01\n" +
	"\x14ProcessActionRequest\x129\n" +
	"\taction_id\x18\x01 \x01(\v2\x1c.google.protobuf.UInt64ValueR\bactionId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12(\n" +
	"\x10action_data_json\x18\x03 \x01(\tR\x0eactionDataJson\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampJ\x04\b\x04\x10\x05\"k\n" +
	"\x15ProcessActionResponse\x12R\n" +
	"\bverdicts\x18\x02 \x01(\v26.osprey.rpc.osprey_coordinator.sync_action.v1.VerdictsR\bverdicts2\xbf\x01\n" +
	"\"OspreyCoordinatorSyncActionService\x12\x98\x01\n" +
	"\rProcessAction\x12B.osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionRequest\x1aC.osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionResponseBQZOgithub.com/yoyo-kid/agent-action-control/internal/policy/osprey/rpc/v1;ospreyv1b\x06proto3"

var (
	file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescOnce sync.Once
	file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescData []byte
)

func file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescGZIP() []byte {
	file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescOnce.Do(func() {
		file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_policy_osprey_rpc_v1_osprey_proto_rawDesc), len(file_internal_policy_osprey_rpc_v1_osprey_proto_rawDesc)))
	})
	return file_internal_policy_osprey_rpc_v1_osprey_proto_rawDescData
}

var file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_policy_osprey_rpc_v1_osprey_proto_goTypes = []any{
	(*Verdicts)(nil),               // 0: osprey.rpc.osprey_coordinator.sync_action.v1.Verdicts
	(*ProcessActionRequest)(nil),   // 1: osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionRequest
	(*ProcessActionResponse)(nil),  // 2: osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*wrapperspb.UInt64Value)(nil), // 4: google.protobuf.UInt64Value
}
var file_internal_policy_osprey_rpc_v1_osprey_proto_depIdxs = []int32{
	3, // 0: osprey.rpc.osprey_coordinator.sync_action.v1.Verdicts.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionRequest.action_id:type_name -> google.protobuf.UInt64Value
	3, // 2: osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionResponse.verdicts:type_name -> osprey.rpc.osprey_coordinator.sync_action.v1.Verdicts
	1, // 4: osprey.rpc.osprey_coordinator.sync_action.v1.OspreyCoordinatorSyncActionService.ProcessAction:input_type -> osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionRequest
	2, // 5: osprey.rpc.osprey_coordinator.sync_action.v1.OspreyCoordinatorSyncActionService.ProcessAction:output_type -> osprey.rpc.osprey_coordinator.sync_action.v1.ProcessActionResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_policy_osprey_rpc_v1_osprey_proto_init() }
func file_internal_policy_osprey_rpc_v1_osprey_proto_init() {
	if File_internal_policy_osprey_rpc_v1_osprey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_policy_osprey_rpc_v1_osprey_proto_rawDesc), len(file_internal_policy_osprey_rpc_v1_osprey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_policy_osprey_rpc_v1_osprey_proto_goTypes,
		DependencyIndexes: file_internal_policy_osprey_rpc_v1_osprey_proto_depIdxs,
		MessageInfos:      file_internal_policy_osprey_rpc_v1_osprey_proto_msgTypes,
	}.Build()
	File_internal_policy_osprey_rpc_v1_osprey_proto = out.File
	file_internal_policy_osprey_rpc_v1_osprey_proto_goTypes = nil
	file_internal_policy_osprey_rpc_v1_osprey_proto_depIdxs = nil
}
