// Wire-compatible subset of Osprey's synchronous coordinator API.
// Source: github.com/roostorg/osprey at 1581a02 (Apache-2.0).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/policy/osprey/rpc/v1/osprey.proto

package ospreyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OspreyCoordinatorSyncActionService_ProcessAction_FullMethodName = "/osprey.rpc.osprey_coordinator.sync_action.v1.OspreyCoordinatorSyncActionService/ProcessAction"
)

// OspreyCoordinatorSyncActionServiceClient is the client API for OspreyCoordinatorSyncActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OspreyCoordinatorSyncActionServiceClient interface {
	ProcessAction(ctx context.Context, in *ProcessActionRequest, opts ...grpc.CallOption) (*ProcessActionResponse, error)
}

type ospreyCoordinatorSyncActionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOspreyCoordinatorSyncActionServiceClient(cc grpc.ClientConnInterface) OspreyCoordinatorSyncActionServiceClient {
	return &ospreyCoordinatorSyncActionServiceClient{cc}
}

func (c *ospreyCoordinatorSyncActionServiceClient) ProcessAction(ctx context.Context, in *ProcessActionRequest, opts ...grpc.CallOption) (*ProcessActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessActionResponse)
	err := c.cc.Invoke(ctx, OspreyCoordinatorSyncActionService_ProcessAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OspreyCoordinatorSyncActionServiceServer is the server API for OspreyCoordinatorSyncActionService service.
// All implementations must embed UnimplementedOspreyCoordinatorSyncActionServiceServer
// for forward compatibility.
type OspreyCoordinatorSyncActionServiceServer interface {
	ProcessAction(context.Context, *ProcessActionRequest) (*ProcessActionResponse, error)
	mustEmbedUnimplementedOspreyCoordinatorSyncActionServiceServer()
}

// UnimplementedOspreyCoordinatorSyncActionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOspreyCoordinatorSyncActionServiceServer struct{}

func (UnimplementedOspreyCoordinatorSyncActionServiceServer) ProcessAction(context.Context, *ProcessActionRequest) (*ProcessActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessAction not implemented")
}
func (UnimplementedOspreyCoordinatorSyncActionServiceServer) mustEmbedUnimplementedOspreyCoordinatorSyncActionServiceServer() {
}
func (UnimplementedOspreyCoordinatorSyncActionServiceServer) testEmbeddedByValue() {}

// UnsafeOspreyCoordinatorSyncActionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OspreyCoordinatorSyncActionServiceServer will
// result in compilation errors.
type UnsafeOspreyCoordinatorSyncActionServiceServer interface {
	mustEmbedUnimplementedOspreyCoordinatorSyncActionServiceServer()
}

func RegisterOspreyCoordinatorSyncActionServiceServer(s grpc.ServiceRegistrar, srv OspreyCoordinatorSyncActionServiceServer) {
	// If the following call panics, it indicates UnimplementedOspreyCoordinatorSyncActionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OspreyCoordinatorSyncActionService_ServiceDesc, srv)
}

func _OspreyCoordinatorSyncActionService_ProcessAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OspreyCoordinatorSyncActionServiceServer).ProcessAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OspreyCoordinatorSyncActionService_ProcessAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OspreyCoordinatorSyncActionServiceServer).ProcessAction(ctx, req.(*ProcessActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OspreyCoordinatorSyncActionService_ServiceDesc is the grpc.ServiceDesc for OspreyCoordinatorSyncActionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OspreyCoordinatorSyncActionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osprey.rpc.osprey_coordinator.sync_action.v1.OspreyCoordinatorSyncActionService",
	HandlerType: (*OspreyCoordinatorSyncActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAction",
			Handler:    _OspreyCoordinatorSyncActionService_ProcessAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/policy/osprey/rpc/v1/osprey.proto",
}
